# Generated by Django 5.1.1 on 2024-09-12 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=10)),
                ('products', models.JSONField()),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(choices=[(0, 'Factory'), (1, 'Retail Network'), (2, 'Individual Entrepreneur')])),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.supplier')),
            ],
        ),
    ]
